# Python stubs generated by omniidl from cine.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "Cine"
#
__name__ = "Cine"
_0_Cine = omniORB.openModule("Cine", r"cine.idl")
_0_Cine__POA = omniORB.openModule("Cine__POA", r"cine.idl")


# struct Pelicula
_0_Cine.Pelicula = omniORB.newEmptyClass()
class Pelicula (omniORB.StructBase):
    _NP_RepositoryId = "IDL:Cine/Pelicula:1.0"

    def __init__(self, id, titulo, genero, duracion):
        self.id = id
        self.titulo = titulo
        self.genero = genero
        self.duracion = duracion

_0_Cine.Pelicula = Pelicula
_0_Cine._d_Pelicula  = (omniORB.tcInternal.tv_struct, Pelicula, Pelicula._NP_RepositoryId, "Pelicula", "id", omniORB.tcInternal.tv_long, "titulo", (omniORB.tcInternal.tv_string,0), "genero", (omniORB.tcInternal.tv_string,0), "duracion", omniORB.tcInternal.tv_long)
_0_Cine._tc_Pelicula = omniORB.tcInternal.createTypeCode(_0_Cine._d_Pelicula)
omniORB.registerType(Pelicula._NP_RepositoryId, _0_Cine._d_Pelicula, _0_Cine._tc_Pelicula)
del Pelicula

# struct Sala
_0_Cine.Sala = omniORB.newEmptyClass()
class Sala (omniORB.StructBase):
    _NP_RepositoryId = "IDL:Cine/Sala:1.0"

    def __init__(self, id, nombre, filas, columnas):
        self.id = id
        self.nombre = nombre
        self.filas = filas
        self.columnas = columnas

_0_Cine.Sala = Sala
_0_Cine._d_Sala  = (omniORB.tcInternal.tv_struct, Sala, Sala._NP_RepositoryId, "Sala", "id", omniORB.tcInternal.tv_long, "nombre", (omniORB.tcInternal.tv_string,0), "filas", omniORB.tcInternal.tv_long, "columnas", omniORB.tcInternal.tv_long)
_0_Cine._tc_Sala = omniORB.tcInternal.createTypeCode(_0_Cine._d_Sala)
omniORB.registerType(Sala._NP_RepositoryId, _0_Cine._d_Sala, _0_Cine._tc_Sala)
del Sala

# struct Funcion
_0_Cine.Funcion = omniORB.newEmptyClass()
class Funcion (omniORB.StructBase):
    _NP_RepositoryId = "IDL:Cine/Funcion:1.0"

    def __init__(self, id, peliculaId, salaId, fecha, hora):
        self.id = id
        self.peliculaId = peliculaId
        self.salaId = salaId
        self.fecha = fecha
        self.hora = hora

_0_Cine.Funcion = Funcion
_0_Cine._d_Funcion  = (omniORB.tcInternal.tv_struct, Funcion, Funcion._NP_RepositoryId, "Funcion", "id", omniORB.tcInternal.tv_long, "peliculaId", omniORB.tcInternal.tv_long, "salaId", omniORB.tcInternal.tv_long, "fecha", (omniORB.tcInternal.tv_string,0), "hora", (omniORB.tcInternal.tv_string,0))
_0_Cine._tc_Funcion = omniORB.tcInternal.createTypeCode(_0_Cine._d_Funcion)
omniORB.registerType(Funcion._NP_RepositoryId, _0_Cine._d_Funcion, _0_Cine._tc_Funcion)
del Funcion

# struct Asiento
_0_Cine.Asiento = omniORB.newEmptyClass()
class Asiento (omniORB.StructBase):
    _NP_RepositoryId = "IDL:Cine/Asiento:1.0"

    def __init__(self, fila, columna, ocupado):
        self.fila = fila
        self.columna = columna
        self.ocupado = ocupado

_0_Cine.Asiento = Asiento
_0_Cine._d_Asiento  = (omniORB.tcInternal.tv_struct, Asiento, Asiento._NP_RepositoryId, "Asiento", "fila", omniORB.tcInternal.tv_long, "columna", omniORB.tcInternal.tv_long, "ocupado", omniORB.tcInternal.tv_boolean)
_0_Cine._tc_Asiento = omniORB.tcInternal.createTypeCode(_0_Cine._d_Asiento)
omniORB.registerType(Asiento._NP_RepositoryId, _0_Cine._d_Asiento, _0_Cine._tc_Asiento)
del Asiento

# struct Boleto
_0_Cine.Boleto = omniORB.newEmptyClass()
class Boleto (omniORB.StructBase):
    _NP_RepositoryId = "IDL:Cine/Boleto:1.0"

    def __init__(self, id, funcionId, fila, columna, nombreCliente, precio):
        self.id = id
        self.funcionId = funcionId
        self.fila = fila
        self.columna = columna
        self.nombreCliente = nombreCliente
        self.precio = precio

_0_Cine.Boleto = Boleto
_0_Cine._d_Boleto  = (omniORB.tcInternal.tv_struct, Boleto, Boleto._NP_RepositoryId, "Boleto", "id", omniORB.tcInternal.tv_long, "funcionId", omniORB.tcInternal.tv_long, "fila", omniORB.tcInternal.tv_long, "columna", omniORB.tcInternal.tv_long, "nombreCliente", (omniORB.tcInternal.tv_string,0), "precio", omniORB.tcInternal.tv_double)
_0_Cine._tc_Boleto = omniORB.tcInternal.createTypeCode(_0_Cine._d_Boleto)
omniORB.registerType(Boleto._NP_RepositoryId, _0_Cine._d_Boleto, _0_Cine._tc_Boleto)
del Boleto

# typedef ... ListaPeliculas
class ListaPeliculas:
    _NP_RepositoryId = "IDL:Cine/ListaPeliculas:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_Cine.ListaPeliculas = ListaPeliculas
_0_Cine._d_ListaPeliculas  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:Cine/Pelicula:1.0"], 0)
_0_Cine._ad_ListaPeliculas = (omniORB.tcInternal.tv_alias, ListaPeliculas._NP_RepositoryId, "ListaPeliculas", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:Cine/Pelicula:1.0"], 0))
_0_Cine._tc_ListaPeliculas = omniORB.tcInternal.createTypeCode(_0_Cine._ad_ListaPeliculas)
omniORB.registerType(ListaPeliculas._NP_RepositoryId, _0_Cine._ad_ListaPeliculas, _0_Cine._tc_ListaPeliculas)
del ListaPeliculas

# typedef ... ListaSalas
class ListaSalas:
    _NP_RepositoryId = "IDL:Cine/ListaSalas:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_Cine.ListaSalas = ListaSalas
_0_Cine._d_ListaSalas  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:Cine/Sala:1.0"], 0)
_0_Cine._ad_ListaSalas = (omniORB.tcInternal.tv_alias, ListaSalas._NP_RepositoryId, "ListaSalas", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:Cine/Sala:1.0"], 0))
_0_Cine._tc_ListaSalas = omniORB.tcInternal.createTypeCode(_0_Cine._ad_ListaSalas)
omniORB.registerType(ListaSalas._NP_RepositoryId, _0_Cine._ad_ListaSalas, _0_Cine._tc_ListaSalas)
del ListaSalas

# typedef ... ListaFunciones
class ListaFunciones:
    _NP_RepositoryId = "IDL:Cine/ListaFunciones:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_Cine.ListaFunciones = ListaFunciones
_0_Cine._d_ListaFunciones  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:Cine/Funcion:1.0"], 0)
_0_Cine._ad_ListaFunciones = (omniORB.tcInternal.tv_alias, ListaFunciones._NP_RepositoryId, "ListaFunciones", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:Cine/Funcion:1.0"], 0))
_0_Cine._tc_ListaFunciones = omniORB.tcInternal.createTypeCode(_0_Cine._ad_ListaFunciones)
omniORB.registerType(ListaFunciones._NP_RepositoryId, _0_Cine._ad_ListaFunciones, _0_Cine._tc_ListaFunciones)
del ListaFunciones

# typedef ... ListaAsientos
class ListaAsientos:
    _NP_RepositoryId = "IDL:Cine/ListaAsientos:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_Cine.ListaAsientos = ListaAsientos
_0_Cine._d_ListaAsientos  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:Cine/Asiento:1.0"], 0)
_0_Cine._ad_ListaAsientos = (omniORB.tcInternal.tv_alias, ListaAsientos._NP_RepositoryId, "ListaAsientos", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:Cine/Asiento:1.0"], 0))
_0_Cine._tc_ListaAsientos = omniORB.tcInternal.createTypeCode(_0_Cine._ad_ListaAsientos)
omniORB.registerType(ListaAsientos._NP_RepositoryId, _0_Cine._ad_ListaAsientos, _0_Cine._tc_ListaAsientos)
del ListaAsientos

# typedef ... ListaBoletos
class ListaBoletos:
    _NP_RepositoryId = "IDL:Cine/ListaBoletos:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_Cine.ListaBoletos = ListaBoletos
_0_Cine._d_ListaBoletos  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:Cine/Boleto:1.0"], 0)
_0_Cine._ad_ListaBoletos = (omniORB.tcInternal.tv_alias, ListaBoletos._NP_RepositoryId, "ListaBoletos", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:Cine/Boleto:1.0"], 0))
_0_Cine._tc_ListaBoletos = omniORB.tcInternal.createTypeCode(_0_Cine._ad_ListaBoletos)
omniORB.registerType(ListaBoletos._NP_RepositoryId, _0_Cine._ad_ListaBoletos, _0_Cine._tc_ListaBoletos)
del ListaBoletos

# typedef ... ListaNumeros
class ListaNumeros:
    _NP_RepositoryId = "IDL:Cine/ListaNumeros:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_Cine.ListaNumeros = ListaNumeros
_0_Cine._d_ListaNumeros  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_long, 0)
_0_Cine._ad_ListaNumeros = (omniORB.tcInternal.tv_alias, ListaNumeros._NP_RepositoryId, "ListaNumeros", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_long, 0))
_0_Cine._tc_ListaNumeros = omniORB.tcInternal.createTypeCode(_0_Cine._ad_ListaNumeros)
omniORB.registerType(ListaNumeros._NP_RepositoryId, _0_Cine._ad_ListaNumeros, _0_Cine._tc_ListaNumeros)
del ListaNumeros

# exception ErrorValidacion
_0_Cine.ErrorValidacion = omniORB.newEmptyClass()
class ErrorValidacion (CORBA.UserException):
    _NP_RepositoryId = "IDL:Cine/ErrorValidacion:1.0"

    def __init__(self, mensaje):
        CORBA.UserException.__init__(self, mensaje)
        self.mensaje = mensaje

_0_Cine.ErrorValidacion = ErrorValidacion
_0_Cine._d_ErrorValidacion  = (omniORB.tcInternal.tv_except, ErrorValidacion, ErrorValidacion._NP_RepositoryId, "ErrorValidacion", "mensaje", (omniORB.tcInternal.tv_string,0))
_0_Cine._tc_ErrorValidacion = omniORB.tcInternal.createTypeCode(_0_Cine._d_ErrorValidacion)
omniORB.registerType(ErrorValidacion._NP_RepositoryId, _0_Cine._d_ErrorValidacion, _0_Cine._tc_ErrorValidacion)
del ErrorValidacion

# interface SistemaCine
_0_Cine._d_SistemaCine = (omniORB.tcInternal.tv_objref, "IDL:Cine/SistemaCine:1.0", "SistemaCine")
omniORB.typeMapping["IDL:Cine/SistemaCine:1.0"] = _0_Cine._d_SistemaCine
_0_Cine.SistemaCine = omniORB.newEmptyClass()
class SistemaCine :
    _NP_RepositoryId = _0_Cine._d_SistemaCine[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Cine.SistemaCine = SistemaCine
_0_Cine._tc_SistemaCine = omniORB.tcInternal.createTypeCode(_0_Cine._d_SistemaCine)
omniORB.registerType(SistemaCine._NP_RepositoryId, _0_Cine._d_SistemaCine, _0_Cine._tc_SistemaCine)

# SistemaCine operations and attributes
SistemaCine._d_crearPelicula = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_long, ), {_0_Cine.ErrorValidacion._NP_RepositoryId: _0_Cine._d_ErrorValidacion})
SistemaCine._d_obtenerPeliculas = ((), (omniORB.typeMapping["IDL:Cine/ListaPeliculas:1.0"], ), None)
SistemaCine._d_obtenerPelicula = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:Cine/Pelicula:1.0"], ), {_0_Cine.ErrorValidacion._NP_RepositoryId: _0_Cine._d_ErrorValidacion})
SistemaCine._d_crearSala = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_long, ), {_0_Cine.ErrorValidacion._NP_RepositoryId: _0_Cine._d_ErrorValidacion})
SistemaCine._d_obtenerSalas = ((), (omniORB.typeMapping["IDL:Cine/ListaSalas:1.0"], ), None)
SistemaCine._d_obtenerSala = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:Cine/Sala:1.0"], ), {_0_Cine.ErrorValidacion._NP_RepositoryId: _0_Cine._d_ErrorValidacion})
SistemaCine._d_crearFuncion = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_Cine.ErrorValidacion._NP_RepositoryId: _0_Cine._d_ErrorValidacion})
SistemaCine._d_obtenerFunciones = ((), (omniORB.typeMapping["IDL:Cine/ListaFunciones:1.0"], ), None)
SistemaCine._d_obtenerFuncionesPorFecha = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:Cine/ListaFunciones:1.0"], ), None)
SistemaCine._d_obtenerFuncion = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:Cine/Funcion:1.0"], ), {_0_Cine.ErrorValidacion._NP_RepositoryId: _0_Cine._d_ErrorValidacion})
SistemaCine._d_obtenerAsientosFuncion = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:Cine/ListaAsientos:1.0"], ), {_0_Cine.ErrorValidacion._NP_RepositoryId: _0_Cine._d_ErrorValidacion})
SistemaCine._d_generarBoleto = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_double), (omniORB.tcInternal.tv_long, ), {_0_Cine.ErrorValidacion._NP_RepositoryId: _0_Cine._d_ErrorValidacion})
SistemaCine._d_generarBoletosMultiples = ((omniORB.tcInternal.tv_long, omniORB.typeMapping["IDL:Cine/ListaNumeros:1.0"], omniORB.typeMapping["IDL:Cine/ListaNumeros:1.0"], (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_double), (omniORB.typeMapping["IDL:Cine/ListaBoletos:1.0"], ), {_0_Cine.ErrorValidacion._NP_RepositoryId: _0_Cine._d_ErrorValidacion})
SistemaCine._d_obtenerBoleto = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:Cine/Boleto:1.0"], ), {_0_Cine.ErrorValidacion._NP_RepositoryId: _0_Cine._d_ErrorValidacion})
SistemaCine._d_obtenerTodosBoletos = ((), (omniORB.typeMapping["IDL:Cine/ListaBoletos:1.0"], ), None)

# SistemaCine object reference
class _objref_SistemaCine (CORBA.Object):
    _NP_RepositoryId = SistemaCine._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def crearPelicula(self, *args):
        return self._obj.invoke("crearPelicula", _0_Cine.SistemaCine._d_crearPelicula, args)

    def obtenerPeliculas(self, *args):
        return self._obj.invoke("obtenerPeliculas", _0_Cine.SistemaCine._d_obtenerPeliculas, args)

    def obtenerPelicula(self, *args):
        return self._obj.invoke("obtenerPelicula", _0_Cine.SistemaCine._d_obtenerPelicula, args)

    def crearSala(self, *args):
        return self._obj.invoke("crearSala", _0_Cine.SistemaCine._d_crearSala, args)

    def obtenerSalas(self, *args):
        return self._obj.invoke("obtenerSalas", _0_Cine.SistemaCine._d_obtenerSalas, args)

    def obtenerSala(self, *args):
        return self._obj.invoke("obtenerSala", _0_Cine.SistemaCine._d_obtenerSala, args)

    def crearFuncion(self, *args):
        return self._obj.invoke("crearFuncion", _0_Cine.SistemaCine._d_crearFuncion, args)

    def obtenerFunciones(self, *args):
        return self._obj.invoke("obtenerFunciones", _0_Cine.SistemaCine._d_obtenerFunciones, args)

    def obtenerFuncionesPorFecha(self, *args):
        return self._obj.invoke("obtenerFuncionesPorFecha", _0_Cine.SistemaCine._d_obtenerFuncionesPorFecha, args)

    def obtenerFuncion(self, *args):
        return self._obj.invoke("obtenerFuncion", _0_Cine.SistemaCine._d_obtenerFuncion, args)

    def obtenerAsientosFuncion(self, *args):
        return self._obj.invoke("obtenerAsientosFuncion", _0_Cine.SistemaCine._d_obtenerAsientosFuncion, args)

    def generarBoleto(self, *args):
        return self._obj.invoke("generarBoleto", _0_Cine.SistemaCine._d_generarBoleto, args)

    def generarBoletosMultiples(self, *args):
        return self._obj.invoke("generarBoletosMultiples", _0_Cine.SistemaCine._d_generarBoletosMultiples, args)

    def obtenerBoleto(self, *args):
        return self._obj.invoke("obtenerBoleto", _0_Cine.SistemaCine._d_obtenerBoleto, args)

    def obtenerTodosBoletos(self, *args):
        return self._obj.invoke("obtenerTodosBoletos", _0_Cine.SistemaCine._d_obtenerTodosBoletos, args)

omniORB.registerObjref(SistemaCine._NP_RepositoryId, _objref_SistemaCine)
_0_Cine._objref_SistemaCine = _objref_SistemaCine
del SistemaCine, _objref_SistemaCine

# SistemaCine skeleton
__name__ = "Cine__POA"
class SistemaCine (PortableServer.Servant):
    _NP_RepositoryId = _0_Cine.SistemaCine._NP_RepositoryId


    _omni_op_d = {"crearPelicula": _0_Cine.SistemaCine._d_crearPelicula, "obtenerPeliculas": _0_Cine.SistemaCine._d_obtenerPeliculas, "obtenerPelicula": _0_Cine.SistemaCine._d_obtenerPelicula, "crearSala": _0_Cine.SistemaCine._d_crearSala, "obtenerSalas": _0_Cine.SistemaCine._d_obtenerSalas, "obtenerSala": _0_Cine.SistemaCine._d_obtenerSala, "crearFuncion": _0_Cine.SistemaCine._d_crearFuncion, "obtenerFunciones": _0_Cine.SistemaCine._d_obtenerFunciones, "obtenerFuncionesPorFecha": _0_Cine.SistemaCine._d_obtenerFuncionesPorFecha, "obtenerFuncion": _0_Cine.SistemaCine._d_obtenerFuncion, "obtenerAsientosFuncion": _0_Cine.SistemaCine._d_obtenerAsientosFuncion, "generarBoleto": _0_Cine.SistemaCine._d_generarBoleto, "generarBoletosMultiples": _0_Cine.SistemaCine._d_generarBoletosMultiples, "obtenerBoleto": _0_Cine.SistemaCine._d_obtenerBoleto, "obtenerTodosBoletos": _0_Cine.SistemaCine._d_obtenerTodosBoletos}

SistemaCine._omni_skeleton = SistemaCine
_0_Cine__POA.SistemaCine = SistemaCine
omniORB.registerSkeleton(SistemaCine._NP_RepositoryId, SistemaCine)
del SistemaCine
__name__ = "Cine"

#
# End of module "Cine"
#
__name__ = "cine_idl"

_exported_modules = ( "Cine", )

# The end.
