# DO NOT EDIT THIS FILE!
#
# Python module Cine__POA generated by omniidl

import omniORB
omniORB.updateModule("Cine__POA")

# ** 1. Stub files contributing to this module
import cine_idl

# ** 2. Sub-modules

# ** 3. End
